### ISSUE TITLE
Disable Save All

### ISSUE THREAD

**Issue by trymeouteh** [TypeFox/open-collaboration-tools#45]
To disable the Save All feature when collaborating. This will prevent user A from saving an inactive tab that another user is working on to reduce conflicts.

I have my editor setup for when I press CTRL + S, that it will Save All, not save the current file. However I think during collaboration that the Save All should be disabled.

**Comment by msujew** [comment]
Is this specifically for the VS Code extension? We cannot disable commands that are registered by VS Code itself.

**Comment by msujew** [comment]
Right now, it doesn't actually do anything. You'll find that a guest cannot actually write to the host file system (or save a file for that matter):

https://github.com/TypeFox/open-collaboration-tools/blob/e2503da2e9cfa3ad16c9dbe225f5933074278cda/packages/open-collaboration-vscode/src/collaboration-file-system.ts#L51-L53

**Comment by msujew** [comment]
This will be closed once https://github.com/TypeFox/open-collaboration-tools/pull/51 is merged. Saving a file as a guest should also save the file on the host system.
