### ISSUE TITLE
[VSCode] Binary file sharing support

### ISSUE THREAD

**Issue by akenejie** [TypeFox/open-collaboration-tools#48]
I have been using the Live Share extension to collaboratively edit LaTeX, but have always had trouble viewing image and PDF files.

https://github.com/microsoft/live-share/issues/1895

What I would like to request is similar to this issue. If this is resolved, it would be an advantage that Live Share does not have!
Thank you.

**Comment by msujew** [comment]
I'm not sure what kind of architecture Microsoft is using internally for their live share feature (it's closed source after all), but I'm a bit confused why they haven't fixed it after 5 (!) years. Anyway, see PR https://github.com/TypeFox/open-collaboration-tools/pull/51 for a fix for that.
