### ISSUE TITLE
[VSCode] Cursor and binary file auto-reload do not work with Unicode filenames

### ISSUE THREAD

**Issue by akenejie** [TypeFox/open-collaboration-tools#69]
When co-editing a file name that contains Unicode characters (e.g., `テスト.tex`), the cursor is not displayed.
Also, automatic reloading of binary files (e.g., `テスト.pdf`) will not work.

**Comment by msujew** [comment]
This has been fixed in #70 and published with 0.2.4 of the VS Code extension.
