### ISSUE TITLE
Unable to Create Session with Own Server Despite Firewall Rule for Port 8100

### ISSUE THREAD

**Issue by B4t4l10n** [TypeFox/open-collaboration-tools#74]
**Description:**
I am experiencing an issue where a session cannot be successfully created when using our own server, even though port 8100 has been opened in the firewall. The login page is accessible, but the session is not established properly.

**Steps to Reproduce:**
1. Clone the repository using `git clone`.
2. Build the project as described in the README using `npm build`.
3. Run the project and try to access the login page.
4. Attempt to log in and create a session.

**Expected Behavior:**
A session should be created successfully after logging in, allowing the API to be accessed and browsed.

**Actual Behavior:**
- The initial login page is reachable.
- However, the session is not created successfully.
- The API cannot be accessed or browsed after logging in.
- The firewall has been configured to allow traffic through port 8100.
- There are no visible errors during the build process.
- No API response is observed after attempting to log in.

**Screenshots:**
![image](https://github.com/user-attachments/assets/6c893502-dd4d-4996-ad14-c71323a255a4)
![image](https://github.com/user-attachments/assets/91066958-b902-4c9d-81a0-07b54b9332bc)

**Comment by msujew** [comment]
Hey @B4t4l10n,

To enable the anonymous login, you need to set the `OCT_ACTIVATE_SIMPLE_LOGIN` to `true`:

https://github.com/TypeFox/open-collaboration-tools/blob/86f2afd71aa2b935f9cbdecc969fcbc2ba4f9cf0/.vscode/launch.json#L24

https://github.com/TypeFox/open-collaboration-tools/blob/86f2afd71aa2b935f9cbdecc969fcbc2ba4f9cf0/packages/open-collaboration-server/src/auth-endpoints/simple-login-endpoint.ts#L24-L26

**Comment by B4t4l10n** [comment]
Hi @msujew,

Thank you for your feedback. Actually I thought, that the ENV variable gets set during the npm run, as the variable is set in the run config. Ok, now it works. This issue can then be closed.


All the best (Beste Grüße aus HH ;) )
